version: "3"
services:
  server:
    build: .
    environment:
      - EXTERNAL_API_URL=http://172.29.208.1:5000
      - JWT_SECRET=secret
      - DATABASE_URL=mongodb+srv://admin:5040%2BEnvio%3A%29@guruhotel.vsfi2kg.mongodb.net/guruhotel?retryWrites=true&w=majority
    ports:
      - 4000:4000
    expose:
      - 4000
    
   
