version: "3"
services:
  server:
    build: .
    environment:
      - EXTERNAL_API_URL=yourExternalAPIHere
      - JWT_SECRET=yourSecretHere
      - DATABASE_URL=yourmongodbConnectionstringHere
    ports:
      - 4000:4000
    expose:
      - 4000
    
   
